# Site settings
title: Fit4Tots
email: info@fit4tots.com
#telephone: 07875026420
telephone: 0777xxxxxx
description: ''
baseurl: ''
url: 'http://www.fit4tots.com' # the base hostname & protocol for your site
twitter_username: fit4tots
facebook_username: fit4totsUK
cloudinary_prefix: 'http://res.cloudinary.com/fit4tots/image/upload'
timezone: Europe/London

environment: production

# Build settings
markdown: kramdown

exclude: ['*.html.haml', 'js/**/*', 'css/**/*', 'Gemfile', 'Gemfile.lock', 'pre-commit.sh', 'Rakefile', 'Guardfile', '*.sublime-project']

sass:
  style: :compressed